stages:
  - build
  - deploy

job_build:
  stage: build
  script:
    - sh ./build.sh $CI_COMMIT_REF_NAME

job_deploy:
  stage: deploy
  script:
    - cd /opt/analytics_server/
    - docker compose pull
    - docker compose down
    - docker compose up -d