profile: dev

server_host: 0.0.0.0
server_rest_port: 5000


db:
  host: 127.0.0.1
  port: 5432
  database: hack_server
  username: postgres
  password: postgres
  migrations: ./migrations

s3:
  url: 
  login:
  password: 
  bucket: 

panda:
  bootstrap_servers:
    -
  security_protocol: 
  sasl_mechanism: 
  sasl_plain_username:
  sasl_plain_password: 

logging:
  app_name: cc-gate
  graylog:
    enabled: false
    host: localhost
    port: 12201
    udp: true
  console:
    enabled: true
  root_level: INFO
  levels:
    httpx: WARN
    openai: WARN
    uvicorn.access: WARN
    VastController: DEBUG
